MvcBaseDemo/Models/QiniuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using System.IO;

namespace MvcBaseDemo.Models
{
    public class QiniuController : Controller
    {
        private string path = @"E:\Users\Administrator\Pictures\Qiniu\1.jpg";
        //
        // GET: /Qiniu/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadPic()
        {
            QiniuFun qiniuFun = new QiniuFun();
            qiniuFun.init();

            HttpPostedFileBase file = Request.Files["file"];

            //var filenmae = string.Format("{0:yyyyMMddHHmmssfffffff}", DateTime.Now) + ".jpg";

            //qiniuFun.UploadFile(qiniuFun.qnSpace, qiniuFun.fullname("/" + filenmae), path);
            //var name = qiniuFun.outlink + qiniuFun.fullname("/" + filenmae);
            //return Json("Success|" + name);

            Response.Write("文件统计 : "+Request.Files.Count);

            ViewBag.test = Request.Form["test1"];
            if (file != null)
            {
                var filenmae = string.Format("{0:yyyyMMddHHmmssfffffff}", DateTime.Now) + ".jpg";

                string filePath = Path.Combine(HttpContext.Server.MapPath("Images/Uploads"), Path.GetFileName(filenmae));
                file.SaveAs(filePath);

                qiniuFun.UploadFile(qiniuFun.qnSpace, qiniuFun.fullname("/" + filenmae), filePath);
                var name = qiniuFun.outlink + qiniuFun.fullname("/" + filenmae);

                return Json("Success|" + name);
            }
            else
            {
                return View();
            }
        }

    }
}

MvcBaseDemo/Views/Qiniu/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("UploadPic", "Qiniu", new { FormMethod = "Post", enctype = "multipart/form-data", id = "uploadForm" }))
        {
            <ol>
                <li>       
                    <input type="text" value="" name="test1" id="test1"/>     
                </li>
                <li>
                    <input type="file" value="上传图片" name="file1" id="file1" />
                    <input type="file" id="file" name="file" class="up-file" />
                </li>
            </ol>           
            
            <input type="button" value="上传" />
        }

        @using (@Ajax.BeginForm("UploadPic", "Qiniu", "", new AjaxOptions { OnSuccess = "uplOnSuccess", OnBegin = "SubChk" }, new { FormMethod = "Post", enctype = "multipart/form-data", id = "uploadForm" }))
        {
            @Html.AntiForgeryToken();//防伪标记
            @Html.ValidationSummary(true, "", new { @class = "" })//验证错误提示

                                            <div class="form-group">
                                                <label>上传图片：</label>
                                                <div class="my-upload">
                                                    <div class="up-img">
                                                        <input type="file" id="file" name="file" class="up-file" />
                                                    </div>
                                                    @*<img src="~/Images/demoing/nb_1.jpg" alt="" />*@
                                                </div>
                                                <span>上传图片</span>
                                            </div>
        }
    </div>
    @Scripts.Render("~/Scripts/jquery-1.8.2.min.js")

    <script>
        $("input[type=file]").change(function () {
            var file = this.files[0];
            var imgsrc = webkitURL.createObjectURL(file);

            var formData=new FormData($("uploadForm")[0]);

            $.ajax({
                url: '/Qiniu/UploadPic',
                type: 'POST',
                data: formData,
                async: true,
                cache: false,
                contentType: false,
                processData: false,
                beforeSend: function () {
                    console.log("开始发送请求!");
                },
                success: function (returnData) {
                    console.log(returnData.split('|')[1]);
                },
                error: function () {
                    console.log("请求出错!");
                }
            })
        })
    </script>
</body>
</html>

MvcBaseDemo/Views/Qiniu/UploadPic.cshtml
@{
    ViewBag.Title = "UploadPic";
}

<h2>UploadPic</h2>